### PR TITLE
Disable agent when opcache is in reset pending state (#988)

### LINKED ISSUE #988: Agent creates a 502 on cache clear within WordPress Admin
**Describe the bug**
When clearing cache using the popular W3 Total Cache plugin while APM agent is active (latest version, but older versions too), the page will react in one of three ways. One, by throwing a large number of APM errors within the plugin page. Two, by displaying a critical error on the page (along with the DB login info). Three, a generic Nginx 502.

1. 
image

2. 
image

3.
image

All of these will resolve after page refresh. 

When the APM agent is disabled, cache clear behaves normally. 

Notable logs during that time:

`myContainer       | 2023/06/08 20:23:46 [error] 27#27: *101 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.22.0.1, server: , request: "GET /wp-admin/admin.php?page=w3tc_dashboard&w3tc_note=flush_all HTTP/1.1", upstream: "fastcgi://unix:/tmp/.php-fpm.sock:", host: "localhost:8080", referrer: "http://localhost:8080/wp-admin/admin.php?page=w3tc_dashboard&w3tc_note=flush_all"`

Notable errors on page during that time:

`Warning: Invalid callback \Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::interceptedCallPreHook, class "\Elastic\Apm\Impl\AutoInstrument\PhpPartFacade" not found in /var/www/html/wp-includes/class-wpdb.php on line 2431`

`Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/class-wpdb.php:942) in /var/www/html/wp-admin/includes/misc.php on line 1431`

Really nothing weird being output by the Agent logs, even in Debug mode. 

<details open>
<summary>Agent Debug Logs</summary>
 [Elastic APM PHP Tracer] 2023-06-08 20:13:22.919606+00:00 [PID: 540] [TID: 540] [DEBUG]    [Lifecycle] [lifecycle.c:563] [elasticApmRequestInit] Entered; parent PID: 534
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.919629+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [ConfigManager.c:1513] [ensureConfigManagerHasLatestConfig] Current configuration is already the latest
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.920827+00:00 [PID: 540] [TID: 540] [DEBUG]    [C-to-PHP] [tracer_PHP_part.c:41] [bootstrapTracerPhpPart] Entered; config->bootstrapPhpPartFile: `/opt/elastic/apm-agent-php/src/bootstrap_php_part.php'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.920846+00:00 [PID: 540] [TID: 540] [DEBUG]    [Util] [util_for_PHP.c:50] [loadPhpFile] Entered; phpFilePath: `/opt/elastic/apm-agent-php/src/bootstrap_php_part.php'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.921430+00:00 [PID: 540] [TID: 540] [DEBUG]    [Util] [util_for_PHP.c:164] [loadPhpFile] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.921451+00:00 [PID: 540] [TID: 540] [DEBUG]    [Util] [util_for_PHP.c:190] [callPhpFunction] Entered; phpFunctionName: `\Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::bootstrap', argsCount: 2
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.921473+00:00 [PID: 540] [TID: 540] [DEBUG]    [Bootstrap] [BootstrapStageLogger.php:98] [bootstrap] Starting bootstrap sequence... maxEnabledLogLevel: 5
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924832+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"api_key","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924873+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"async_backend_comm","Option default value":true,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924900+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"breakdown_metrics","Option default value":true,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924924+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"capture_errors","Option default value":true,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924950+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"dev_internal","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.924984+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"disable_instrumentations","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925018+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"disable_send","Option default value":false,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925057+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"enabled","Raw value":"1","Parsed value":true,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925087+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"environment","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925111+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"hostname","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925137+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"log_level","Raw value":"debug","Parsed value":5,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925161+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"log_level_stderr","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925186+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"log_level_syslog","Raw value":"debug","Parsed value":5,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925210+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"non_keyword_string_max_length","Option default value":10240,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925234+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"profiling_inferred_spans_enabled","Option default value":false,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925258+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"profiling_inferred_spans_min_duration","Option default value":0,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925283+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"profiling_inferred_spans_sampling_interval","Option default value":1000,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925327+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"sanitize_field_names","Option default value":{"type":"Elastic\\Apm\\Impl\\Util\\WildcardListMatcher","value_as_string":"password, passwd, pwd, secret, *key, *token*, *session*, *credit*, *card*, *auth*, set-cookie"},"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925361+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"secret_token","Raw value":"","Parsed value":"","namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925392+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"server_timeout","Option default value":30000,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925458+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"service_name","Raw value":"pgibbs1","Parsed value":"pgibbs1","namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925498+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"service_node_name","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925534+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:89] [parse] Input raw config snapshot has a value - using parsed value {"Option name":"service_version","Raw value":"","Parsed value":"","namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925565+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"transaction_ignore_urls","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925596+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"transaction_max_spans","Option default value":500,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925634+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"transaction_sample_rate","Option default value":1,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925666+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"url_groups","Option default value":null,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.925696+00:00 [PID: 540] [TID: 540] [DEBUG]    [Configuration] [Parser.php:80] [parse] Input raw config snapshot doesn't have a value for the option - using default value {"Option name":"verify_server_cert","Option default value":true,"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.926612+00:00 [PID: 540] [TID: 540] [DEBUG]    [Public-API] [Tracer.php:104] [__construct] Constructing Tracer... {"Version of agent PHP part":"1.8.3","PHP_VERSION":"8.1.19","providedDependencies":{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null},"effectiveLogLevel":"DEBUG","namespace":"Elastic\\Apm\\Impl","class":"Tracer","this":{"isRecording":true,"providedDependencies":{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null},"config":{"optNameToParsedValue":{"api_key":null,"async_backend_comm":true,"breakdown_metrics":true,"capture_errors":true,"dev_internal":null,"disable_instrumentations":null,"disable_send":false,"enabled":true,"environment":null,"hostname":null,"log_level":5,"log_level_stderr":null,"log_level_syslog":5,"non_keyword_string_max_length":10240,"profiling_inferred_spans_enabled":false,"profiling_inferred_spans_min_duration":0,"profiling_inferred_spans_sampling_interval":1000,"sanitize_field_names":{"type":"Elastic\\Apm\\Impl\\Util\\WildcardListMatcher","value_as_string":"password, passwd, pwd, secret, *key, *token*, *session*, *credit*, *card*, *auth*, set-cookie"},"secret_token":"","server_timeout":30000,"service_name":"pgibbs1","service_node_name":null,"service_version":"","transaction_ignore_urls":null,"transaction_max_spans":500,"transaction_sample_rate":1,"url_groups":null,"verify_server_cert":true},"apiKey":null,"asyncBackendComm":true,"breakdownMetrics":true,"captureErrors":true,"devInternal":null,"devInternalParsed":{"dropEventAfterEnd":false,"dropEventsBeforeSendCCode":false,"gcCollectCyclesAfterEveryTransaction":false,"gcMemCachesAfterEveryTransaction":false},"disableInstrumentations":null,"disableSend":false,"enabled":true,"environment":null,"hostname":null,"logLevel":5,"logLevelStderr":null,"logLevelSyslog":5,"nonKeywordStringMaxLength":10240,"profilingInferredSpansEnabled":false,"profilingInferredSpansMinDuration":0,"profilingInferredSpansSamplingInterval":1000,"sanitizeFieldNames":{"type":"Elastic\\Apm\\Impl\\Util\\WildcardListMatcher","value_as_string":"password, passwd, pwd, secret, *key, *token*, *session*, *credit*, *card*, *auth*, set-cookie"},"secretToken":"","serverTimeout":30000,"serviceName":"pgibbs1","serviceNodeName":null,"serviceVersion":"","transactionIgnoreUrls":null,"transactionMaxSpans":500,"transactionSampleRate":1,"urlGroups":null,"verifyServerCert":true,"effectiveLogLevel":5}}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.928086+00:00 [PID: 540] [TID: 540] [DEBUG]    [Public-API] [Tracer.php:128] [__construct] Constructed Tracer successfully {"namespace":"Elastic\\Apm\\Impl","class":"Tracer","this":{"isRecording":true,"providedDependencies":{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null},"config":{"optNameToParsedValue":{"api_key":null,"async_backend_comm":true,"breakdown_metrics":true,"capture_errors":true,"dev_internal":null,"disable_instrumentations":null,"disable_send":false,"enabled":true,"environment":null,"hostname":null,"log_level":5,"log_level_stderr":null,"log_level_syslog":5,"non_keyword_string_max_length":10240,"profiling_inferred_spans_enabled":false,"profiling_inferred_spans_min_duration":0,"profiling_inferred_spans_sampling_interval":1000,"sanitize_field_names":{"type":"Elastic\\Apm\\Impl\\Util\\WildcardListMatcher","value_as_string":"password, passwd, pwd, secret, *key, *token*, *session*, *credit*, *card*, *auth*, set-cookie"},"secret_token":"","server_timeout":30000,"service_name":"pgibbs1","service_node_name":null,"service_version":"","transaction_ignore_urls":null,"transaction_max_spans":500,"transaction_sample_rate":1,"url_groups":null,"verify_server_cert":true},"apiKey":null,"asyncBackendComm":true,"breakdownMetrics":true,"captureErrors":true,"devInternal":null,"devInternalParsed":{"dropEventAfterEnd":false,"dropEventsBeforeSendCCode":false,"gcCollectCyclesAfterEveryTransaction":false,"gcMemCachesAfterEveryTransaction":false},"disableInstrumentations":null,"disableSend":false,"enabled":true,"environment":null,"hostname":null,"logLevel":5,"logLevelStderr":null,"logLevelSyslog":5,"nonKeywordStringMaxLength":10240,"profilingInferredSpansEnabled":false,"profilingInferredSpansMinDuration":0,"profilingInferredSpansSamplingInterval":1000,"sanitizeFieldNames":{"type":"Elastic\\Apm\\Impl\\Util\\WildcardListMatcher","value_as_string":"password, passwd, pwd, secret, *key, *token*, *session*, *credit*, *card*, *auth*, set-cookie"},"secretToken":"","serverTimeout":30000,"serviceName":"pgibbs1","serviceNodeName":null,"serviceVersion":"","transactionIgnoreUrls":null,"transactionMaxSpans":500,"transactionSampleRate":1,"urlGroups":null,"verifyServerCert":true,"effectiveLogLevel":5}}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.928696+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [TransactionForExtensionRequest.php:447] [discoverCliName] Using CLI script name as transaction name {"cliScriptName":"Standard input code","argc":1,"argv":["Standard input code"],"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"TransactionForExtensionRequest","this":{"type":"Elastic\\Apm\\Impl\\AutoInstrument\\TransactionForExtensionRequest","object_ID":3,"object_hash":"00000000000000030000000000000000"}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.928897+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [TransactionForExtensionRequest.php:570] [discoverStartTime] Using requestInitStartTime for transaction start time because $_SERVER['REQUEST_TIME_FLOAT'] is later (further into the future) than requestInitStartTime {"requestInitStartTime":1686255202919605,"$_SERVER['REQUEST_TIME_FLOAT']":1686255202920826,"$_SERVER['REQUEST_TIME_FLOAT'] - requestInitStartTime (seconds)":0.001221,"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"TransactionForExtensionRequest","this":{"type":"Elastic\\Apm\\Impl\\AutoInstrument\\TransactionForExtensionRequest","object_ID":3,"object_hash":"00000000000000030000000000000000"}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.928956+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [TransactionForExtensionRequest.php:629] [getHttpHeader] Incoming traceparent HTTP request header not found {"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"TransactionForExtensionRequest","this":{"type":"Elastic\\Apm\\Impl\\AutoInstrument\\TransactionForExtensionRequest","object_ID":3,"object_hash":"00000000000000030000000000000000"}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.929889+00:00 [PID: 540] [TID: 540] [DEBUG]    [Distributed-Tracing] [HttpDistributedTracing.php:135] [parseHeadersImpl] Found no traceparent HTTP header so there is nothing to parse {"namespace":"Elastic\\Apm\\Impl","class":"HttpDistributedTracing","traceParentHeaderValues":[],"traceStateHeaderValues":[]}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.930220+00:00 [PID: 540] [TID: 540] [DEBUG]    [Public-API] [ExecutionSegment.php:172] [__construct] Exiting... {"systemClockNow":1686255202930019,"timestampArg":1686255202919605,"systemClockNow - timestampArg (seconds)":0.010414,"namespace":"Elastic\\Apm\\Impl","class":"ExecutionSegment","this":{"currentSpanId":null,"parentId":null,"startedSpansCount":0,"droppedSpansCount":0,"result":null,"isSampled":null,"context":null,"numberOfErrorsSent":0,"breakdownMetricsPerTransaction":{"transaction":{"currentSpanId":null,"parentId":null,"startedSpansCount":0,"droppedSpansCount":0,"result":null,"isSampled":null,"context":null,"numberOfErrorsSent":0,"breakdownMetricsPerTransaction":{"transaction":{"Max depth reached":10,"type":"array","count":26},"perSpanTypeData":[]},"outgoingTraceState":"es=s:1","onAboutToEnd":null,"onCurrentSpanChanged":null,"name":"Standard input code","type":"cli","id":"346f5853ff3f062f","traceId":"0d70a2a95e6f76ef5098dea6487796a8","timestamp":1686255202919605,"duration":null,"outcome":null,"sampleRate":1,"isDiscarded":false,"breakdownMetricsSelfTimeTracker":{"currentSelfTimeSegmentBeginTime":31435210602,"runningChildrenCount":0,"accumulatedSelfTimeInMicroseconds":0},"diffStartTimeWithSystemClockOnBeginInMicroseconds":10414,"systemClockBeginTime":1686255202930019,"monotonicBeginTime":31435210602,"isEnded":false},"perSpanTypeData":[]},"outgoingTraceState":"es=s:1","onAboutToEnd":null,"onCurrentSpanChanged":null,"name":"Standard input code","type":"cli","id":"346f5853ff3f062f","traceId":"0d70a2a95e6f76ef5098dea6487796a8","timestamp":1686255202919605,"duration":null,"outcome":null,"sampleRate":1,"isDiscarded":false,"breakdownMetricsSelfTimeTracker":{"currentSelfTimeSegmentBeginTime":31435210602,"runningChildrenCount":0,"accumulatedSelfTimeInMicroseconds":0},"diffStartTimeWithSystemClockOnBeginInMicroseconds":10414,"systemClockBeginTime":1686255202930019,"monotonicBeginTime":31435210602,"isEnded":false}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.930390+00:00 [PID: 540] [TID: 540] [DEBUG]    [Public-API] [Transaction.php:142] [__construct] Transaction created {"namespace":"Elastic\\Apm\\Impl","class":"Transaction","this":{"currentSpanId":null,"parentId":null,"startedSpansCount":0,"droppedSpansCount":0,"result":null,"isSampled":true,"context":null,"numberOfErrorsSent":0,"breakdownMetricsPerTransaction":{"transaction":{"currentSpanId":null,"parentId":null,"startedSpansCount":0,"droppedSpansCount":0,"result":null,"isSampled":true,"context":null,"numberOfErrorsSent":0,"breakdownMetricsPerTransaction":{"transaction":{"Max depth reached":10,"type":"array","count":26},"perSpanTypeData":[]},"outgoingTraceState":"es=s:1","onAboutToEnd":{"callbacks count":0},"onCurrentSpanChanged":{"callbacks count":0},"name":"Standard input code","type":"cli","id":"346f5853ff3f062f","traceId":"0d70a2a95e6f76ef5098dea6487796a8","timestamp":1686255202919605,"duration":null,"outcome":null,"sampleRate":1,"isDiscarded":false,"breakdownMetricsSelfTimeTracker":{"currentSelfTimeSegmentBeginTime":31435210602,"runningChildrenCount":0,"accumulatedSelfTimeInMicroseconds":0},"diffStartTimeWithSystemClockOnBeginInMicroseconds":10414,"systemClockBeginTime":1686255202930019,"monotonicBeginTime":31435210602,"isEnded":false},"perSpanTypeData":[]},"outgoingTraceState":"es=s:1","onAboutToEnd":{"callbacks count":0},"onCurrentSpanChanged":{"callbacks count":0},"name":"Standard input code","type":"cli","id":"346f5853ff3f062f","traceId":"0d70a2a95e6f76ef5098dea6487796a8","timestamp":1686255202919605,"duration":null,"outcome":null,"sampleRate":1,"isDiscarded":false,"breakdownMetricsSelfTimeTracker":{"currentSelfTimeSegmentBeginTime":31435210602,"runningChildrenCount":0,"accumulatedSelfTimeInMicroseconds":0},"diffStartTimeWithSystemClockOnBeginInMicroseconds":10414,"systemClockBeginTime":1686255202930019,"monotonicBeginTime":31435210602,"isEnded":false}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.930776+00:00 [PID: 540] [TID: 540] [DEBUG]    [Inferred-Spans] [InferredSpansManager.php:83] [__construct] Entered {"namespace":"Elastic\\Apm\\Impl","class":"InferredSpansManager","this":{"currentTransactionId":null,"state":"shutdown","originalPcntlAsyncSignalsEnabled":null,"builder":null,"onNewCurrentTransactionHasBegunCallback":null,"onCurrentTransactionAboutToEndCallback":null,"onCurrentSpanChangedCallback":null}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.930825+00:00 [PID: 540] [TID: 540] [DEBUG]    [Inferred-Spans] [InferredSpansManager.php:115] [detectIfEnabled] Inferred spans feature is disabled because configuration option profiling_inferred_spans_enabled value is false {"namespace":"Elastic\\Apm\\Impl","class":"InferredSpansManager","this":{"currentTransactionId":null,"state":"shutdown","originalPcntlAsyncSignalsEnabled":null,"builder":null,"onNewCurrentTransactionHasBegunCallback":null,"onCurrentTransactionAboutToEndCallback":null,"onCurrentSpanChangedCallback":null}}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932479+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [PluginBase.php:55] [__construct] Instrumentation curl is enabled {"instrumentation other names":["http-client"],"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"PluginBase"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932514+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [PluginBase.php:55] [__construct] Instrumentation pdo is enabled {"instrumentation other names":["db"],"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"PluginBase"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932547+00:00 [PID: 540] [TID: 540] [DEBUG]    [Auto-Instrumentation] [PluginBase.php:55] [__construct] Instrumentation mysqli is enabled {"instrumentation other names":["db"],"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"PluginBase"}
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932577+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_init'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932593+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 0
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932672+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_setopt'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932690+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 1
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932713+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_setopt_array'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932729+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 2
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932750+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_copy_handle'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932766+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 3
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932785+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_exec'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932802+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 4
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932822+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `curl_close'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932839+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 5
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932861+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_connect'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932878+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 6
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932898+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `__construct'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932916+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932936+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_select_db'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932953+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 8
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932973+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `select_db'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.932991+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933010+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933026+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 10
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933046+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933064+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933082+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_multi_query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933100+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 12
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933119+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `multi_query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933137+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933156+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_real_query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933174+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 14
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933193+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `real_query'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933211+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933230+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_prepare'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933246+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 16
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933266+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `prepare'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933283+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933302+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_stmt_execute'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933319+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 18
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933338+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli_stmt'; methodName: `execute'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933356+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933375+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_ping'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933392+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 20
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933412+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `ping'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933429+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933448+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_begin_transaction'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933464+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 22
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933484+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `begin_transaction'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933501+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933520+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_commit'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933536+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 24
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933556+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `commit'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933573+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933592+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_rollback'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933609+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 26
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933633+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `rollback'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933652+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933671+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:213] [elasticApmInterceptCallsToInternalFunctionEx] Entered; functionName: `mysqli_kill'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933687+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:234] [elasticApmInterceptCallsToInternalFunctionEx] Exiting...; resultCode: resultSuccess (0); interceptRegistrationId: 28
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933707+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:174] [elasticApmInterceptCallsToInternalMethod] Entered; className: `mysqli'; methodName: `kill'
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933725+00:00 [PID: 540] [TID: 540] [DEBUG]    [Ext-API] [elastic_apm_API.c:204] [elasticApmInterceptCallsToInternalMethod] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933746+00:00 [PID: 540] [TID: 540] [DEBUG]    [Bootstrap] [BootstrapStageLogger.php:124] [bootstrap] Successfully completed bootstrap sequence
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933763+00:00 [PID: 540] [TID: 540] [DEBUG]    [Util] [util_for_PHP.c:223] [callPhpFunction] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933780+00:00 [PID: 540] [TID: 540] [DEBUG]    [C-to-PHP] [tracer_PHP_part.c:82] [bootstrapTracerPhpPart] Exiting...; resultCode: resultSuccess (0); 
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933798+00:00 [PID: 540] [TID: 540] [DEBUG]    [Lifecycle] [lifecycle.c:617] [elasticApmRequestInit] Set zend_error_cb: 0x56261ae138c5 (!= elasticApmZendErrorCallback) -> 0x7f8a38db1c53
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933817+00:00 [PID: 540] [TID: 540] [DEBUG]    [Lifecycle] [lifecycle.c:624] [elasticApmRequestInit] Set zend_throw_exception_hook: 0 (!= elasticApmZendThrowExceptionHook) -> 0x7f8a38db09c8
[Elastic APM PHP Tracer] 2023-06-08 20:13:22.933837+00:00 [PID: 540] [TID: 540] [DEBUG]    [Lifecycle] [lifecycle.c:636] [elasticApmRequestInit] Exiting...; resultCode: resultSuccess (0); 
</details>

**To Reproduce**

1. Running two containers: WordpressDB:mysql:8, and Wordpress:latest. 
2. Set up the APM agent via your preferred method to run in the Wordpress container (I used APK, but it occurs via other methods too)
3. Login to your local wordpress env and install the W3 Total Cache plugin, activate it. 
4. Run "clear all cache" or "clear op cache"
5. Errors should throw.

**Expected behavior**
Cache clearing handled gracefully

This has been ongoing for at least 6 months since we adopted the PHP APM agent, took a look at the repo but I'm not a PHP guru so my own solutions were lost. I've tried altering timeouts on all systems, increasing / decreasing workers, other system management techinques, etc.. but I can't escape the error.

### PR DESCRIPTION
**Pull request by intuibase**
Fixes #988

### CODE REVIEW

File: src/ext/util_for_PHP.c [hunk 1]
```diff
@@ -274,6 +274,61 @@ bool isPhpRunningAsCliScript()
...
+        zval_ptr_dtor(&rv);
+        return false;
+    }
+
+    if (Z_TYPE(rv) != IS_ARRAY) {
+        zval_ptr_dtor(&rv);
+        return false;
+    }
+
+	zval *restartPending = zend_hash_str_find(Z_ARRVAL(rv), ZEND_STRL("restart_pending"));
```
Comment (SergeyKleyman) [inline src/ext/util_for_PHP.c:322]: [There's also `restart_in_progress` key](https://www.php.net/manual/en/function.opcache-get-status.php) - should we check for that as well?

File: src/ext/util_for_PHP.c [hunk 2]
```diff
@@ -274,6 +274,61 @@ bool isPhpRunningAsCliScript()
...
+    }
+
+	zval rv;
+    ZVAL_NULL(&rv);
+	zval parameters[1];
+	ZVAL_BOOL(&parameters[0], false);
+
+    int result = call_internal_function(NULL, "opcache_get_status", parameters, 1, &rv);
+    if (result == resultFailure) {
+        zval_ptr_dtor(&rv);
```
Comment (SergeyKleyman) [inline src/ext/util_for_PHP.c:313]: Maybe it's worth using `goto finally` approach to avoid duplicating cleaning code (`zval_ptr_dtor(&rv);`)?

File: src/ext/lifecycle.c [hunk 3]
```diff
@@ -652,6 +654,12 @@ void elasticApmRequestInit()
         ELASTIC_APM_SET_RESULT_CODE_AND_GOTO_FAILURE();
     }
 
+    if (detectOpcacheRestartPending()) {
```
Comment (SergeyKleyman) [inline src/ext/lifecycle.c:657]: What do you think about adding `tracerPhpPartState_disabled` to `enum TracerPhpPartState` and set state to it here?

File: src/ext/tracer_PHP_part.c [hunk 4]
```diff
@@ -75,17 +75,18 @@ String tracerPhpPartStateToString( TracerPhpPartState value )
 
 static TracerPhpPartState g_tracerPhpPartState = numberOfTracerPhpPartState;
 
-void switchTracerPhpPartStateToFailed( String reason, String dbgCalledFromFunc )
+bool switchTracerPhpPartStateToFailed( String reason, String dbgCalledFromFunc )
```
Comment (SergeyKleyman) [inline src/ext/tracer_PHP_part.c:78]: WDYT about

1. Adding `bool canInvokeTracerPhpPart()`
2. Have return false on `tracerPhpPartState_disabled` and `tracerPhpPartState_failed`
3. Check `canInvokeTracerPhpPart()` at beginning of each function that invokes PHP part

**Review by SergeyKleyman — APPROVED** [review]

File: src/ext/util_for_PHP.c (hunk 2 above)
Comment (intuibase) [reply src/ext/util_for_PHP.c:313]: true, i'll update it when we will introduce c++
